INSERT INTO tb_user(USERNAME, NIVEL) VALUES('Clayton', 'admin');
INSERT INTO tb_user(USERNAME, NIVEL) VALUES('Claudia', 'user');
INSERT INTO tb_user(USERNAME, NIVEL) VALUES('Gabriela', 'user');
INSERT INTO tb_user(USERNAME, NIVEL) VALUES('Micaela', 'admin');

INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','ORIENTAÇÃO MÉDICA', 'PENDENTE', 'CAMINHAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','MATEMATICA', 'EM_ANDAMENTO', 'ESTUDAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','EDUCADOR FISICO', 'CONCLUIDA', 'PEDALAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','PERDER PESO', 'PENDENTE', 'CORRER');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','TRABALHO', 'EM_ANDAMENTO', 'PROGRAMAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','HOBBY', 'CONCLUIDA', 'PINTAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','CASA', 'PENDENTE', 'ORGANIZAR');
INSERT INTO tb_task(CREATEDAT, DUE_DATE, DESCRIPTION, STATUS, TITLE) VALUES('2024-09-03', '2024-09-30','QUARTOS', 'EM_ANDAMENTO', 'ARRUMAR');